owner: laksithaudayanga1110
repo: dtech-web-monitoring

sites:
  - name: DSI
    url: http://dsi.lk/
  - name: DTech LK
    url: http://dtech.lk/
  - name: DTech COM
    url: http://dtechlk.com
  - name: DSS
    url: http://www.dss.lk/
  - name: Samtessi Brush
    url: http://samtessibrush.lk/
  - name: Lanka Brush
    url: http://lankabrush.com/
  - name: SML Footwear
    url: https://smlfootwear.com/
  - name: Primo LK
    url: http://www.primolk.com/
  - name: Grant Tech Holdings
    url: http://granttechholdings.com/
  - name: Grace LK
    url: http://gracelk.com/
  - name: BNB Furnitures
    url: https://bnbfurnitureslk.com/
  - name: Sheet Piling Sri Lanka
    url: http://sheetpilingsrilanka.com/
  - name: Rajendra Trading
    url: http://rajendratrading.com/
  - name: Hummingbird Holiday
    url: http://hummingbirdholiday.com/
  - name: Hummingbird LK
    url: http://hummingbird.lk/
  - name: Ursidekick
    url: http://ursidekick.com/
  - name: Vandanaa
    url: http://vandanaa.lk/
  - name: Zynolo LK
    url: http://zynolo.lk/
  - name: Zynolo COM
    url: http://zynolo.com/
  - name: Social Cookie
    url: http://www.socialcookie.lk/
  - name: Araksha LK
    url: https://araksha.lk/
  - name: Samson Lines
    url: https://samsonlines.lk/
  - name: Ceylan Inc
    url: https://ceylaninc.com/
  - name: Samson Compounds
    url: https://samsoncompounds.com/
  - name: Spectrum Campus
    url: https://spectrumcampus.edu.lk/
  - name: Legante Law
    url: https://legantelaw.com/
  - name: Agasti Store
    url: https://agastistore.lk/
  - name: Holiday Connex
    url: https://holidayconnex.com/
  - name: Devi Jewellers
    url: https://devijewellers.lk/
  - name: Wickramaratnes
    url: https://wickramaratnes.com/
  - name: Office Plus
    url: https://officeplus.mv/
  - name: Lucksons
    url: https://lucksons.lk/
  - name: DSI Energy
    url: http://dsienergy.lk/

status-website:
  baseUrl: /dtech-web-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DTech Web Monitoring
  introTitle: "Live Websites Status"
  introMessage: "Real-time monitoring and status report for our live production websites."
  navbar:
    - title: Status
      href: /dtech-web-monitoring
    - title: GitHub
      href: https://github.com/laksithaudayanga1110/dtech-web-monitoring
